import type { CompanyContent } from "./company-content.types"

export const DEFAULT_COMPANY_CONTENT: CompanyContent = {
  privacyPolicy: {
    title: "Politicas de privacidad",
    content:
      "# Aviso de Privacidad Integral - INHALEX\n\n## Responsable del tratamiento\n\nINHALEX S.A.S. de C.V. es responsable del tratamiento de tus datos personales.\n\n- Correo de contacto: danielcruzhernandezinhaleX@gmail.com\n- Domicilio para notificaciones: [pendiente]\n- Telefono: [pendiente]\n\nINHALEX desarrolla y comercializa productos naturales y opera un sitio web y aplicacion movil.\n\n## 1. Que datos personales recabamos\n\nSegun como interactues con la plataforma, podemos tratar:\n\n1. Identificacion y contacto (nombre, correo, telefono, pais/estado y datos de facturacion).\n2. Cuenta y autenticacion (credenciales cifradas y preferencias basicas).\n3. Envio y facturacion (domicilios de entrega/factura y referencias).\n4. Transacciones (productos, importes, cupones, fecha/hora y tokens de pago).\n5. Soporte y comunicaciones (mensajes por email/chat/WhatsApp y encuestas).\n6. Datos tecnicos y de uso (IP, dispositivo, sistema operativo, zona horaria, logs y cookies).\n\nNo almacenamos numeros completos de tarjeta. El cobro se procesa mediante pasarelas de pago externas.\n\n## 2. Finalidades del tratamiento\n\n### a) Finalidades necesarias\n\n- Crear y administrar tu cuenta.\n- Vender, cobrar, facturar y entregar productos.\n- Gestionar cambios, devoluciones y garantias.\n- Brindar soporte y seguimiento.\n- Cumplir obligaciones legales, fiscales y de seguridad.\n- Prevenir fraude y mejorar el rendimiento del servicio.\n\n### b) Finalidades adicionales\n\n- Enviarte promociones y comunicaciones comerciales.\n- Realizar analitica y segmentacion para mejorar productos y campanas.\n\n## 3. Base legal\n\nTratamos tus datos con base en:\n\n- Consentimiento.\n- Relacion contractual.\n- Obligacion legal.\n- Interes legitimo (seguridad y mejora del servicio).\n\n## 4. Medidas de seguridad\n\nImplementamos medidas administrativas, tecnicas y fisicas razonables para proteger la informacion (control de acceso, cifrado en transito, practicas de seguridad y politicas internas).\n\n## 5. Derechos ARCO\n\nPuedes ejercer derechos de Acceso, Rectificacion, Cancelacion y Oposicion por correo.\n\nIncluye:\n\n- Nombre y medio para responderte.\n- Identificacion oficial (o representacion legal).\n- Descripcion clara del derecho que deseas ejercer.\n- Documentos de soporte, si aplican.\n\n## 6. Cookies y tecnologias similares\n\nUsamos cookies/SDKs para:\n\n- Funciones esenciales (sesion, carrito y seguridad).\n- Analitica y rendimiento.\n- Marketing, cuando exista consentimiento.\n\n## 7. Cambios al aviso de privacidad\n\nPodemos actualizar este aviso por cambios legales u operativos. Publicaremos la version vigente con fecha de actualizacion.\n\n## 8. Contacto\n\n- Correo: danielcruzhernandezinhaleX@gmail.com\n- Domicilio: [pendiente]\n- Horario de atencion: [pendiente]",
  },
  termsAndConditions: {
    title: "Terminos y condiciones",
    content:
      "# Terminos y Condiciones - INHALEX\n\nAl acceder, navegar, registrarte o comprar en la plataforma, aceptas estos terminos y condiciones.\n\n## 1. Propiedad intelectual\n\nTodo el contenido del sitio y la app (textos, imagenes, diseños, logotipos, codigo y materiales) es propiedad de INHALEX o sus licenciantes y esta protegido por la ley.\n\n## 2. Precios y especificaciones\n\n- Los precios se muestran en MXN.\n- Pueden cambiar antes de confirmar la compra.\n- Las imagenes son ilustrativas.\n- En caso de error evidente de precio o disponibilidad, INHALEX puede cancelar y reembolsar el pedido.\n\nAviso: los productos no sustituyen atencion medica profesional.\n\n## 3. Pedidos y aceptacion\n\nTu orden constituye una oferta de compra. INHALEX acepta cuando confirma envio o entrega.\n\n## 4. Envio\n\n- Cobertura, paqueterias y tiempos: [pendiente].\n- Costos y politicas de envio: [pendiente].\n- Reporte de danos visibles o faltantes: dentro de 48 horas.\n\n## 5. Devoluciones, cambios y cancelaciones\n\n- Plazo de devolucion: [pendiente].\n- Producto sin abrir y con empaque original, salvo defecto.\n- Sprays abiertos/usados no son retornables salvo defecto de fabrica.\n- Reembolsos al mismo medio de pago segun politica vigente.\n\n## 6. Garantias\n\nSi existe defecto de fabricacion, INHALEX podra sustituir o reembolsar el producto.\n\n## 7. Pago y facturacion\n\n- Medios de pago: [pendiente].\n- No almacenamos numeros completos de tarjeta.\n- Facturacion dentro del mes de compra con datos fiscales correctos.\n\n## 8. Conducta del usuario\n\nEsta prohibido usar la plataforma para fines ilicitos, scraping, ingenieria inversa o abuso del servicio.\n\n## 9. Limitacion de responsabilidad\n\nINHALEX no sera responsable por danos indirectos o eventos fuera de su control en la medida permitida por la ley aplicable.\n\n## 10. Modificaciones\n\nINHALEX puede actualizar estos terminos y publicara la version vigente con su fecha de actualizacion.\n\n## 11. Ley aplicable y jurisdiccion\n\nEstos terminos se rigen por las leyes de Mexico, sin perjuicio de derechos del consumidor ante autoridades competentes.",
  },
  about: {
    mission:
      "En INHALEX nos comprometemos a proporcionar soluciones naturales y efectivas para la salud y el bienestar de nuestros clientes. Nuestro enfoque integra conocimiento tradicional, seleccion de ingredientes y procesos de calidad para ofrecer una alternativa confiable que mejore la calidad de vida de las personas.",
    vision:
      "Ser una empresa lider en el mercado de productos naturales y bienestar, reconocida por su innovacion, calidad y compromiso con la salud de las personas en Mexico y mas alla, construyendo relaciones de confianza a largo plazo con clientes y comunidad.",
    values: [
      "Innovacion",
      "Calidad",
      "Salud y bienestar",
      "Confianza y credibilidad",
    ],
  },
}
